#pragma warning disable CA1711 // Identifiers should not have incorrect suffix

namespace CSharpLatest.Events;

using System;
using System.Threading;
using System.Threading.Tasks;

/// <summary>
/// Represents the method that will handle an event when the event provides data.
/// </summary>
/// <typeparam name="TEventArgs">The type of the event data generated by the event.</typeparam>
/// <param name="sender">The source of the event.</param>
/// <param name="args">An object that contains the event data.</param>
/// <param name="cancellationToken">The cancellation token that will be checked prior to completing the returned task.</param>
public delegate Task AsyncEventHandler<in TEventArgs>(object? sender, TEventArgs args, CancellationToken cancellationToken = default)
    where TEventArgs : EventArgs;
